/* JS */ gapi.loaded_0(function(_){var window=this;
var ua;var ta;var ba;_.q=function(a){return function(){return ba[a].apply(this,arguments)}};_.r=function(a,b){return ba[a]=b};var _DumpException=function(a){throw a;};ba=[];_.ca=_.ca||{};_.s=this;_.fa=function(a){return void 0!==a};
_.ia=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.ka=function(a){return"array"==(0,_.ia)(a)};_.na=function(a){return"string"==typeof a};_.qa="closure_uid_"+(1E9*Math.random()>>>0);ta=function(a,b,c){return a.call.apply(a.bind,arguments)};
ua=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};_.u=function(a,b,c){_.u=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ta:ua;return _.u.apply(null,arguments)};
_.va=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.za=Date.now||function(){return+new Date};_.D=function(a,b){function c(){}c.prototype=b.prototype;a.J=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.zt=function(a,c,f){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}};
_.Da=window.gadgets||{};_.Ea=window.osapi=window.osapi||{};_.google=window.google||{};
window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},client:{jsonpOverride:!1},csi:{rate:0.01},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/:session_prefix:_/widget/render/badge?usegapi=1"},":socialhost:":"https://apis.google.com",":im_socialhost:":"https://plus.googleapis.com",card:{params:{s:"#",userid:"&"},url:":socialhost:/:session_prefix:_/hovercard/internalcard"},
":signuphost:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton?usegapi=1"},plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true&usegapi=1"},plus_circle:{url:":socialhost:/:session_prefix:_/widget/plus/circle?usegapi=1"},plus_followers:{url:":socialhost:/_/im/_/widget/render/plus/followers?usegapi=1"},configurator:{url:":socialhost:/:session_prefix:_/plusbuttonconfigurator?usegapi=1"},appcirclepicker:{url:":socialhost:/:session_prefix:_/widget/render/appcirclepicker"},
page:{url:':socialhost:/:session_prefix:_/widget/render/page?usegapi=1"'},person:{url:':socialhost:/:session_prefix:_/widget/render/person?usegapi=1"'},community:{url:':socialhost:/:session_prefix:_/widget/render/community?usegapi=1"'},follow:{url:":socialhost:/:session_prefix:_/widget/render/follow?usegapi=1"},commentcount:{url:":socialhost:/:session_prefix:_/widget/render/commentcount?usegapi=1"},comments:{url:":socialhost:/:session_prefix:_/widget/render/comments?usegapi=1"},youtube:{url:":socialhost:/:session_prefix:_/widget/render/youtube?usegapi=1"},
reportabuse:{url:":socialhost:/:session_prefix:_/widget/render/reportabuse?usegapi=1"},":source:":"1p"},poclient:{update_session:"google.updateSessionCallback"},"googleapis.config":{methods:{"pos.plusones.list":!0,"pos.plusones.get":!0,"pos.plusones.insert":!0,"pos.plusones.delete":!0,"pos.plusones.getSignupState":!0},requestCache:{enabled:!0},versions:{pos:"v1"},rpc:"/rpc",root:"https://content.googleapis.com","root-1p":"https://clients6.google.com",sessionCache:{enabled:!0},transport:{isProxyShared:!0}, xd3:"/static/proxy.html",developerKey:"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ",auth:{useInterimAuth:!1}},report:{apis:["iframes\\..*","gadgets\\..*","gapi\\.appcirclepicker\\..*","gapi\\.client\\..*"],rate:1E-4}});

_.Fa=function(a,b){return b};_.E=function(a,b){var c=a.split("."),d=_.s;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&(0,_.fa)(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}};_.G=function(a,b){b=(0,_.Fa)(a,b);(0,_.E)(a,b)};
_.Ga=window;_.Ha=window.document;_.Ia=_.Ga.location;_.Ja=/\[native code\]/;_.Ka=function(a,b,c){return a[b]=a[b]||c};_.Ma=function(){var a;if((a=Object.create)&&_.Ja.test(a))a=a(null);else{a={};for(var b in a)a[b]=void 0}return a};_.Na=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};_.Oa=function(a,b){if(!a)throw Error(b||"");};_.Ra=(0,_.Ka)(_.Ga,"gapi",{});
_.Sa=function(a,b,c){var d=new RegExp("([#].*&|[#])"+b+"=([^&#]*)","g");b=new RegExp("([?#].*&|[?#])"+b+"=([^&#]*)","g");if(a=a&&(d.exec(a)||b.exec(a)))try{c=(0,window.decodeURIComponent)(a[2])}catch(e){}return c};_.Xa=function(a,b,c){(0,_.Va)(a,b,c,"add","at")};_.Va=function(a,b,c,d,e){if(a[d+"EventListener"])a[d+"EventListener"](b,c,!1);else if(a[e+"tachEvent"])a[e+"tachEvent"]("on"+b,c)};_.Ya=(0,_.Ka)(_.Ga,"___jsl",(0,_.Ma)());(0,_.Ka)(_.Ya,"I",0);(0,_.Ka)(_.Ya,"hel",10);var db;var cb;var ab;var $a;var Za;Za=function(a){var b=window.___jsl=window.___jsl||{};b[a]=b[a]||[];return b[a]};$a=function(a){var b=window.___jsl=window.___jsl||{};b.cfg=!a&&b.cfg||{};return b.cfg};ab=function(a){return"object"===typeof a&&/\[native code\]/.test(a.push)};
_.bb=function(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&(a[c]&&b[c]&&"object"===typeof a[c]&&"object"===typeof b[c]&&!ab(a[c])&&!ab(b[c])?(0,_.bb)(a[c],b[c]):b[c]&&"object"===typeof b[c]?(a[c]=ab(b[c])?[]:{},(0,_.bb)(a[c],b[c])):a[c]=b[c])};
cb=function(a){if(a&&!/^\s+$/.test(a)){for(;0==a.charCodeAt(a.length-1);)a=a.substring(0,a.length-1);var b;try{b=window.JSON.parse(a)}catch(c){}if("object"===typeof b)return b;try{b=(new Function("return ("+a+"\n)"))()}catch(d){}if("object"===typeof b)return b;try{b=(new Function("return ({"+a+"\n})"))()}catch(e){}return"object"===typeof b?b:{}}};
db=function(a){$a(!0);var b=window.___gcfg,c=Za("cu");if(b&&b!==window.___gu){var d={};(0,_.bb)(d,b);c.push(d);window.___gu=b}var b=Za("cu"),e=window.document.scripts||window.document.getElementsByTagName("script")||[],d=[],f=[];f.push.apply(f,Za("us"));for(var g=0;g<e.length;++g)for(var k=e[g],l=0;l<f.length;++l)k.src&&0==k.src.indexOf(f[l])&&d.push(k);0==d.length&&0<e.length&&e[e.length-1].src&&d.push(e[e.length-1]);for(e=0;e<d.length;++e)d[e].getAttribute("gapi_processed")||(d[e].setAttribute("gapi_processed",
!0),(f=d[e])?(g=f.nodeType,f=3==g||4==g?f.nodeValue:f.textContent||f.innerText||f.innerHTML||""):f=void 0,(f=cb(f))&&b.push(f));a&&(d={},(0,_.bb)(d,a),c.push(d));d=Za("cd");a=0;for(b=d.length;a<b;++a)(0,_.bb)($a(),d[a]);d=Za("ci");a=0;for(b=d.length;a<b;++a)(0,_.bb)($a(),d[a]);a=0;for(b=c.length;a<b;++a)(0,_.bb)($a(),c[a])};_.J=function(a,b){if(!a)return $a();for(var c=a.split("/"),d=$a(),e=0,f=c.length;d&&"object"===typeof d&&e<f;++e)d=d[c[e]];return e===c.length&&void 0!==d?d:b}; _.fb=function(a,b){var c=a;if("string"===typeof a){for(var d=c={},e=a.split("/"),f=0,g=e.length;f<g-1;++f)var k={},d=d[e[f]]=k;d[e[f]]=b}db(c)};
var gb=function(){var a=window.__GOOGLEAPIS;a&&(a.googleapis&&!a["googleapis.config"]&&(a["googleapis.config"]=a.googleapis),(0,_.Ka)(_.Ya,"ci",[]).push(a),window.__GOOGLEAPIS=void 0)};gb&&gb();db();(0,_.G)("gapi.config.get",_.J);(0,_.G)("gapi.config.update",_.fb);
var Hb;var Fb;var Cb;var Ab;var zb;var yb;var wb;var vb;var ub;var tb;var sb;var rb;var qb;var nb;var mb;_.jb=function(a){return!!a&&"object"===typeof a&&_.Ja.test(a.push)};_.kb=function(a,b,c){if(a){(0,_.Oa)((0,_.jb)(a),"arrayForEach was called with a non array value");for(var d=0;d<a.length;d++)b.call(c,a[d],d)}};
_.lb=function(a,b,c){if(a)if((0,_.jb)(a))(0,_.kb)(a,b,c);else{(0,_.Oa)("object"===typeof a,"objectForEach was called with a non object value");c=c||a;for(var d in a)(0,_.Na)(a,d)&&void 0!==a[d]&&b.call(c,a[d],d)}};mb=function(a){a=a.sort();for(var b=[],c=void 0,d=0;d<a.length;d++){var e=a[d];e!=c&&b.push(e);c=e}return b};nb=function(){var a=[],b=_.Ya.H;b&&(0,_.lb)(b,function(b){a.push.apply(a,b.L)});return mb(a)};
_.ob=function(a){if(_.Ja.test(Object.keys))return Object.keys(a);var b=[],c;for(c in a)(0,_.Na)(a,c)&&b.push(c);return b};wb={};yb=0;zb=(0,_.Ma)();Ab=(0,_.Ma)();_.Bb=function(a){if(void 0===qb){var b=(0,_.J)("report")||{},c=b.rate,d=Math.random();if(qb="number"===typeof c&&c>d)Ab["rate."+c+"-"+d]=!0,tb=b.timeout||1E3,rb=b.host||"https://plus.google.com",sb=b.path||"/_/widget/report",vb=b.apis||[]}if(!qb)return!1;if(vb)for(b=0;b<vb.length;b++)if((new RegExp("^"+vb[b]+"$")).test(a))return!0;return!1};
Cb=function(a){delete wb[a]};Fb=function(){ub&&(_.Ga.clearTimeout(ub),ub=0);ub=_.Ga.setTimeout(function(){var a;a=window.document.location;a=a.protocol+"//"+a.host+a.pathname;var b=(0,_.ob)(Ab).join(":");a=[rb,sb,"?api=",(0,window.encodeURIComponent)(b),"&url=",(0,window.encodeURIComponent)(a),"&loaded=",(0,window.encodeURIComponent)(nb().join(":"))].join("");Ab=(0,_.Ma)();var b=new window.Image,c=yb++;wb[c]=b;b.onload=b.onerror=(0,_.va)(Cb,c);b.src=a;ub=0},tb)}; _.Gb=function(a){zb[a]||(Ab[a]=!0,zb[a]=!0,Fb())};Hb=_.Fa;_.Fa=function(a,b){var c=Hb(a,b);"function"===typeof b&&(0,_.Bb)(a)&&(c=function(c){(0,_.Gb)(a);return b.apply(this,arguments)});return c};

_.Ai=window.googleapis&&window.googleapis.server||{};
var Yb;
var Tb={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},Ub=function(a){var b,c,d;b=/[\"\\\x00-\x1f\x7f-\x9f]/g;if(void 0!==a){switch(typeof a){case "string":return b.test(a)?'"'+a.replace(b,function(a){var b=Tb[a];if(b)return b;b=a.charCodeAt();return"\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)})+'"':'"'+a+'"';case "number":return(0,window.isFinite)(a)?String(a):"null";case "boolean":case "null":return String(a);case "object":if(!a)return"null";b=[];if("number"===
typeof a.length&&!a.propertyIsEnumerable("length")){d=a.length;for(c=0;c<d;c+=1)b.push(Ub(a[c])||"null");return"["+b.join(",")+"]"}for(c in a)!/___$/.test(c)&&(0,_.Na)(a,c)&&"string"===typeof c&&(d=Ub(a[c]))&&b.push(Ub(c)+":"+d);return"{"+b.join(",")+"}"}return""}},Vb=function(a){if(!a)return!1;if(/^[\],:{}\s]*$/.test(a.replace(/\\["\\\/b-u]/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}return!1}, Wb=!1;try{Wb=!!window.JSON&&'["a"]'===window.JSON.stringify(["a"])&&"a"===window.JSON.parse('["a"]')[0]}catch(Xb){}Yb=function(a){try{return window.JSON.parse(a)}catch(b){return!1}};_.ac=Wb?window.JSON.stringify:Ub;_.bc=Wb?Yb:Vb;

_.nj=function(){var a=/\s*;\s*/;return{get:function(b,c){for(var d=b+"=",e=(window.document.cookie||"").split(a),f=0,g;g=e[f];++f)if(0==g.indexOf(d))return g.substr(d.length);return c}}}();
_.Mb=function(){function a(a,b){if(!(a<c)&&d)if(2===a&&d.warn)d.warn(b);else if(3===a&&d.error)try{d.error(b)}catch(g){}else d.log&&d.log(b)}var b=function(b){a(1,b)};_.Jb=function(b){a(2,b)};_.Ib=function(b){a(3,b)};_.Lb=function(){};b.INFO=1;b.WARNING=2;b.NONE=4;var c=1,d=window.console?window.console:window.opera?window.opera.postError:void 0;return b}();

_.K=_.K||{};
_.K=_.K||{};(function(){var a=[];_.K.LQ=function(b){a.push(b)};_.K.XQ=function(){for(var b=0,c=a.length;b<c;++b)a[b]()}})();
_.Nb=function(a){for(var b=0;b<this.length;b++)if(this[b]===a)return b;return-1};_.Ob=function(a,b){var c=(0,_.Ka)(_.Ya,"watt",(0,_.Ma)());(0,_.Ka)(c,a,b)};_.K=_.K||{};
(function(){var a=null;_.K.nb=function(b){var c="undefined"===typeof b;if(null!==a&&c)return a;var d={};b=b||window.location.href;var e=b.indexOf("?"),f=b.indexOf("#");b=(-1===f?b.substr(e+1):[b.substr(e+1,f-e-1),"&",b.substr(f+1)].join("")).split("&");for(var e=window.decodeURIComponent?window.decodeURIComponent:window.unescape,f=0,g=b.length;f<g;++f){var k=b[f].indexOf("=");if(-1!==k){var l=b[f].substring(0,k),k=b[f].substring(k+1),k=k.replace(/\+/g," ");try{d[l]=e(k)}catch(m){}}}c&&(a=d);return d}; _.K.nb()})();
(0,_.G)("gadgets.util.getUrlParameters",_.K.nb);
_.Pb=window.console;_.Qb=function(a){_.Pb&&_.Pb.log&&_.Pb.log(a)};_.Rb=function(){};
_.Sb=function(){var a=window.gadgets&&window.gadgets.config&&window.gadgets.config.get;a&&(0,_.fb)(a());return{register:function(a,c,d){d&&d((0,_.J)())},get:function(a){return(0,_.J)(a)},update:function(a,c){if(c)throw"Config replacement is not supported";(0,_.fb)(a)},$a:function(){}}}();
(0,_.G)("gadgets.config.register",_.Sb.register);(0,_.G)("gadgets.config.get",_.Sb.get);(0,_.G)("gadgets.config.init",_.Sb.$a);(0,_.G)("gadgets.config.update",_.Sb.update);
(0,_.G)("gadgets.json.stringify",_.ac);(0,_.G)("gadgets.json.parse",_.bc);(0,_.Sa)(_.Ga.location.href,"rpctoken")&&(0,_.Xa)(_.Ha,"unload",function(){});
var gc;var cc;cc=function(){var a=_.Ha.readyState;return"complete"===a||"interactive"===a&&-1==window.navigator.userAgent.indexOf("MSIE")};_.dc=function(a){if(cc())a();else{var b=!1,c=function(){if(!b)return b=!0,a.apply(this,arguments)};_.Ga.addEventListener?(_.Ga.addEventListener("load",c,!1),_.Ga.addEventListener("DOMContentLoaded",c,!1)):_.Ga.attachEvent&&(_.Ga.attachEvent("onreadystatechange",function(){cc()&&c.apply(this,arguments)}),_.Ga.attachEvent("onload",c))}};_.fc=function(a,b){if(!cc())try{a()}catch(c){}(0,_.dc)(b)}; gc=gc||{};gc.Rx=null;gc.Hw=null;gc.tm=null;gc.frameElement=null;
gc=gc||{};
gc.Yr||(gc.Yr=function(){function a(a){"undefined"!=typeof window.addEventListener?window.addEventListener("message",a,!1):"undefined"!=typeof window.attachEvent&&window.attachEvent("onmessage",a);window.___jsl=window.___jsl||{};var b=window.___jsl;b.RPMQ=b.RPMQ||[];b.RPMQ.push(a)}function b(a){var b=(0,_.bc)(a.data);if(b&&b.f){(0,_.Lb)("gadgets.rpc.receive("+window.name+"): "+a.data);var d=_.M.Mh(b.f);e&&("undefined"!==typeof a.origin?a.origin!==d:a.domain!==/^.+:\/\/([^:]+).*/.exec(d)[1])?(0,_.Ib)("Invalid rpc message origin. "+
d+" vs "+(a.origin||"")):c(b,a.origin)}}var c,d,e=!0;return{oj:function(){return"wpm"},A:function(){return!0},$a:function(f,g){_.Sb.register("rpc",null,function(a){"true"===String((a&&a.rpc||{}).disableForceSecure)&&(e=!1)});c=f;d=g;a(b);d("..",!0);return!0},ib:function(a){d(a,!0);return!0},call:function(a,b,c){var d=_.M.Mh(a),e=_.M.qt(a);d?window.setTimeout(function(){var a=(0,_.ac)(c);(0,_.Lb)("gadgets.rpc.send("+window.name+"): "+a);e.postMessage(a,d)},0):".."!=a&&(0,_.Ib)("No relay set (used as window.postMessage targetOrigin), cannot send cross-domain message"); return!0}}}());
gc=gc||{};
gc.Dl||(gc.Dl=function(){function a(a,b){I[b]=I[b]||function(){a.apply({},arguments)}}function b(){if(null===y&&window.document.body&&m){var a=m+"?cb="+Math.random()+"&origin="+H+"&jsl=1",c=window.document.createElement("div");c.style.height="1px";c.style.width="1px";a='<object height="1" width="1" id="'+l+'" type="application/x-shockwave-flash"><param name="allowScriptAccess" value="always"></param><param name="movie" value="'+a+'"></param><embed type="application/x-shockwave-flash" allowScriptAccess="always" src="'+a+
'" height="1" width="1"></embed></object>';window.document.body.appendChild(c);c.innerHTML=a;y=c.firstChild}++x;null!==v&&(null!==y||50<=x)?window.clearTimeout(v):v=window.setTimeout(b,100)}function c(){z[".."]||(k(".."),C++,50<=C&&null!==F?(window.clearTimeout(F),F=null):F=window.setTimeout(c,100))}function d(){if(null!==y&&y.setup)for(;0<w.length;){var a=w.shift(),b=a.lI;y.setup(a.Ei,".."===b?_.M.Qn:b,".."===b?"INNER":"OUTER")}null!==v&&window.clearTimeout(v);v=null}function e(){z[".."]||null!==
F||(F=window.setTimeout(c,100))}function f(a,b,c){b=_.M.Mh(a);var d=_.M.lj(a);y["sendMessage_"+(".."===a?_.M.Qn:a)+"_"+d+"_"+(".."===a?"INNER":"OUTER")].call(y,(0,_.ac)(c),b);return!0}function g(a,b){var c=(0,_.bc)(a),d=c._scr;d?(t(d,!0),z[d]=!0,".."!==d&&k(d,!0)):window.setTimeout(function(){p(c,b)},0)}function k(a,b){var c=_.M.Qn,d={};d._scr=b?"..":c;d._pnt=c;f(a,0,d)}var l="___xpcswf",m=null,n=!1,p=null,t=null,y=null,w=[],v=null,x=0,C=0,F=null,z={},H=window.location.protocol+"//"+window.location.host,
I;window.___jsl=window.___jsl||{};I=window.___jsl._fm={};_.Sb.register("rpc",null,function(a){n&&(m=a&&a.rpc&&a.rpc.commSwf||"//xpc.googleusercontent.com/gadgets/xpc.swf")});a(d,"ready");a(e,"setupDone");a(g,"receiveMessage");return{oj:function(){return"flash"},A:function(){return!0},$a:function(a,b){p=a;t=b;return n=!0},ib:function(a,c){w.push({Ei:c,lI:a});null===y&&null===v&&(v=window.setTimeout(b,100));return!0},call:f,XB:g,D:d,F:e}}());
if(window.gadgets&&window.gadgets.rpc)"undefined"!=typeof _.M&&_.M||(_.M=window.gadgets.rpc,_.M.config=_.M.config,_.M.register=_.M.register,_.M.$g=_.M.unregister,_.M.Gx=_.M.registerDefault,_.M.jz=_.M.unregisterDefault,_.M.ru=_.M.forceParentVerifiable,_.M.call=_.M.call,_.M.zj=_.M.getRelayUrl,_.M.Qe=_.M.setRelayUrl,_.M.cn=_.M.setAuthToken,_.M.ok=_.M.setupReceiver,_.M.lj=_.M.getAuthToken,_.M.Tq=_.M.removeReceiver,_.M.Qu=_.M.getRelayChannel,_.M.qi=_.M.receive,_.M.Cx=_.M.receiveSameDomain,_.M.va=_.M.getOrigin,
_.M.Mh=_.M.getTargetOrigin,_.M.qt=_.M._getTargetWin,_.M.WB=_.M._parseSiblingId);else{_.M=function(){function a(a,b){if(!Y[a]){var c=ya;b||(c=ja);Y[a]=c;for(var d=da[a]||[],e=0;e<d.length;++e){var f=d[e];f.t=F[a];c.call(a,f.f,f)}da[a]=[]}}function b(){function a(){sa=!0}wa||("undefined"!=typeof window.addEventListener?window.addEventListener("unload",a,!1):"undefined"!=typeof window.attachEvent&&window.attachEvent("onunload",a),wa=!0)}function c(a,c,d,e,f){F[c]&&F[c]===d||((0,_.Ib)("Invalid gadgets.rpc token. "+
F[c]+" vs "+d),La(c,2));f.onunload=function(){I[c]&&!sa&&(La(c,1),_.M.Tq(c))};b();e=(0,_.bc)((0,window.decodeURIComponent)(e))}function d(b,c){if(b&&"string"===typeof b.s&&"string"===typeof b.f&&b.a instanceof Array)if(F[b.f]&&F[b.f]!==b.t&&((0,_.Ib)("Invalid gadgets.rpc token. "+F[b.f]+" vs "+b.t),La(b.f,2)),"__ack"===b.s)window.setTimeout(function(){a(b.f,!0)},0);else{b.c&&(b.callback=function(a){_.M.call(b.f,(b.g?"legacy__":"")+"__cb",null,b.c,a)});if(c){var d=e(c);b.origin=c;var f=b.r,g;try{g=
e(f)}catch(k){}f&&g==d||(f=c);b.referer=f}d=(v[b.s]||v[""]).apply(b,b.a);b.c&&"undefined"!==typeof d&&_.M.call(b.f,"__cb",null,b.c,d)}}function e(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);-1==a.indexOf("://")&&(a=window.location.protocol+"//"+a);var b=a.substring(a.indexOf("://")+3),c=b.indexOf("/");-1!=c&&(b=b.substring(0,c));a=a.substring(0,a.indexOf("://"));if("http"!==a&&"https"!==a&&"chrome-extension"!==a&&"file"!==
a)throw Error("b");var c="",d=b.indexOf(":");if(-1!=d){var e=b.substring(d+1),b=b.substring(0,d);if("http"===a&&"80"!==e||"https"===a&&"443"!==e)c=":"+e}return a+"://"+b+c}function f(a){if("/"==a.charAt(0)){var b=a.indexOf("|");return{id:0<b?a.substring(1,b):a.substring(1),origin:0<b?a.substring(b+1):null}}return null}function g(a){if("undefined"===typeof a||".."===a)return window.parent;var b=f(a);if(b)return window.top.frames[b.id];a=String(a);return(b=window.frames[a])?b:(b=window.document.getElementById(a))&&
b.contentWindow?b.contentWindow:null}function k(a,b){if(!0!==I[a]){"undefined"===typeof I[a]&&(I[a]=0);var c=g(a);".."!==a&&null==c||!0!==ya.ib(a,b)?!0!==I[a]&&10>I[a]++?window.setTimeout(function(){k(a,b)},500):(Y[a]=ja,I[a]=!0):I[a]=!0}}function l(a){(a=x[a])&&"/"===a.substring(0,1)&&(a="/"===a.substring(1,2)?window.document.location.protocol+a:window.document.location.protocol+"//"+window.document.location.host+a);return a}function m(a,b,c){b&&!/http(s)?:\/\/.+/.test(b)&&(0==b.indexOf("//")?b=
window.location.protocol+b:"/"==b.charAt(0)?b=window.location.protocol+"//"+window.location.host+b:-1==b.indexOf("://")&&(b=window.location.protocol+"//"+b));x[a]=b;"undefined"!==typeof c&&(C[a]=!!c)}function n(a,b){b=b||"";F[a]=String(b);k(a,b)}function p(a){a=(a.passReferrer||"").split(":",2);X=a[0]||"none";xa=a[1]||"origin"}function t(b){"true"===String(b.useLegacyProtocol)&&(ya=gc.tm||ja,ya.$a(d,a))}function y(a,b){function c(d){d=d&&d.rpc||{};p(d);var f=d.parentRelayUrl||"",f=e(Q.parent||b)+
f;m("..",f,"true"===String(d.useLegacyProtocol));t(d);n("..",a)}!Q.parent&&b?c({}):_.Sb.register("rpc",null,c)}function w(a,b,c){if(".."===a)y(c||Q.rpctoken||Q.ifpctok||"",b);else t:{var d=null;if("/"!=a.charAt(0)){if(!_.K)break t;d=window.document.getElementById(a);if(!d)throw Error("c`"+a);}d=d&&d.src;b=b||_.M.va(d);m(a,b);b=_.K.nb(d);n(a,c||b.rpctoken)}}var v={},x={},C={},F={},z=0,H={},I={},Q={},Y={},da={},X=null,xa=null,T=window.top!==window.self,la=window.name,La=function(){},$=window.console,
ea=$&&$.log&&function(a){$.log(a)}||function(){},ja=function(){function a(b){return function(){ea(b+": call ignored")}}return{getCode:function(){return"noop"},isParentVerifiable:function(){return!0},init:a("init"),setup:a("setup"),call:a("call")}}();_.K&&(Q=_.K.nb());var sa=!1,wa=!1,ya=function(){if("flash"==Q.rpctx)return gc.Dl;if("rmr"==Q.rpctx)return gc.Rx;var a="function"===typeof window.postMessage?gc.Yr:"object"===typeof window.postMessage?gc.Yr:window.ActiveXObject?gc.Dl?gc.Dl:gc.Hw?gc.Hw:
gc.tm:0<window.navigator.userAgent.indexOf("WebKit")?gc.Rx:"Gecko"===window.navigator.product?gc.frameElement:gc.tm;a||(a=ja);return a}();v[""]=function(){ea("Unknown RPC service: "+this.s)};v.__cb=function(a,b){var c=H[a];c&&(delete H[a],c.call(this,b))};return{config:function(a){"function"===typeof a.Yx&&(La=a.Yx)},register:function(a,b){if("__cb"===a||"__ack"===a)throw Error("d");if(""===a)throw Error("e");v[a]=b},$g:function(a){if("__cb"===a||"__ack"===a)throw Error("f");if(""===a)throw Error("g");
delete v[a]},Gx:function(a){v[""]=a},jz:function(){delete v[""]},ru:function(){},call:function(a,b,c,d){a=a||"..";var e="..";".."===a?e=la:"/"==a.charAt(0)&&(e=_.M.va(window.location.href),e="/"+la+(e?"|"+e:""));++z;c&&(H[z]=c);var g={s:b,f:e,c:c?z:0,a:Array.prototype.slice.call(arguments,3),t:F[a],l:!!C[a]},k;t:if("bidir"===X||"c2p"===X&&".."===a||"p2c"===X&&".."!==a){k=window.location.href;var l="?";if("query"===xa)l="#";else if("hash"===xa)break t;l=k.lastIndexOf(l);l=-1===l?k.length:l;k=k.substring(0,
l)}else k=null;k&&(g.r=k);if(".."===a||null!=f(a)||window.document.getElementById(a))(k=Y[a])||null===f(a)||(k=ya),0===b.indexOf("legacy__")&&(k=ya,g.s=b.substring(8),g.c=g.c?g.c:z),g.g=!0,g.r=e,k?(C[a]&&(k=gc.tm),!1===k.call(a,e,g)&&(Y[a]=ja,ya.call(a,e,g))):da[a]?da[a].push(g):da[a]=[g]},zj:l,Qe:m,cn:n,ok:w,lj:function(a){return F[a]},Tq:function(a){delete x[a];delete C[a];delete F[a];delete I[a];delete Y[a]},Qu:function(){return ya.oj()},qi:function(a,b){4<a.length?ya.XB(a,d):c.apply(null,a.concat(b))},
Cx:function(a){a.a=Array.prototype.slice.call(a.a);window.setTimeout(function(){d(a)},0)},va:e,Mh:function(a){var b=null,c=l(a);c?b=c:(c=f(a))?b=c.origin:b=".."==a?Q.parent:window.document.getElementById(a).src;return e(b)},$a:function(){!1===ya.$a(d,a)&&(ya=ja);T?w(".."):_.Sb.register("rpc",null,function(a){a=a.rpc||{};p(a);t(a)})},qt:g,WB:f,A:"__ack",Qn:la||"..",D:0,C:1,B:2}}();_.M.$a()};
_.M.config({Yx:function(a){throw Error("h`"+a);}});_.Lb=_.Rb;(0,_.G)("gadgets.rpc.config",_.M.config);(0,_.G)("gadgets.rpc.register",_.M.register);(0,_.G)("gadgets.rpc.unregister",_.M.$g);(0,_.G)("gadgets.rpc.registerDefault",_.M.Gx);(0,_.G)("gadgets.rpc.unregisterDefault",_.M.jz);(0,_.G)("gadgets.rpc.forceParentVerifiable",_.M.ru);(0,_.G)("gadgets.rpc.call",_.M.call);(0,_.G)("gadgets.rpc.getRelayUrl",_.M.zj);(0,_.G)("gadgets.rpc.setRelayUrl",_.M.Qe);(0,_.G)("gadgets.rpc.setAuthToken",_.M.cn);(0,_.G)("gadgets.rpc.setupReceiver",_.M.ok);
(0,_.G)("gadgets.rpc.getAuthToken",_.M.lj);(0,_.G)("gadgets.rpc.removeReceiver",_.M.Tq);(0,_.G)("gadgets.rpc.getRelayChannel",_.M.Qu);(0,_.G)("gadgets.rpc.receive",_.M.qi);(0,_.G)("gadgets.rpc.receiveSameDomain",_.M.Cx);(0,_.G)("gadgets.rpc.getOrigin",_.M.va);(0,_.G)("gadgets.rpc.getTargetOrigin",_.M.Mh);

_.Qc=function(a){return"function"==(0,_.ia)(a)};_.Rc=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.Sc=function(a){return"number"==typeof a};_.Tc=2147483648*Math.random()|0;_.N={};_.Uc=window.iframer={};
var cd;var bd;var ad;var $c;var Zc;var Yc;var Xc;_.Vc=function(a,b){return 0==a.lastIndexOf(b,0)};_.Wc=function(a){var b=(0,_.ia)(a);return"array"==b||"object"==b&&"number"==typeof a.length};Xc=/[&<>"']/;Yc=/'/g;Zc=/"/g;$c=/>/g;ad=/</g;bd=/&/g;cd=0;_.dd=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};
_.ed=function(a){if(!Xc.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(bd,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(ad,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace($c,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Zc,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Yc,"&#39;"));return a};_.fd=function(a){return a[_.qa]||(a[_.qa]=++cd)};_.gd=Array.prototype;
_.id=_.gd.indexOf?function(a,b,c){return _.gd.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if((0,_.na)(a))return(0,_.na)(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};_.jd=_.gd.forEach?function(a,b,c){_.gd.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=(0,_.na)(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.kd=_.gd.filter?function(a,b,c){return _.gd.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=(0,_.na)(a)?a.split(""):a,k=0;k<d;k++)if(k in g){var l=g[k];b.call(c,l,k,a)&&(e[f++]=l)}return e};_.ld=_.gd.map?function(a,b,c){return _.gd.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=(0,_.na)(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};
_.md=_.gd.some?function(a,b,c){return _.gd.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=(0,_.na)(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.nd=_.gd.every?function(a,b,c){return _.gd.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=(0,_.na)(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0};_.od=function(a,b){return 0<=(0,_.id)(a,b)};
_.pd=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c],e;if((0,_.ka)(d)||(e=(0,_.Wc)(d))&&Object.prototype.hasOwnProperty.call(d,"callee"))a.push.apply(a,d);else if(e)for(var f=a.length,g=d.length,k=0;k<g;k++)a[f+k]=d[k];else a.push(d)}};

var td;_.qd=function(){};_.rd=function(a,b,c){return 2>=arguments.length?_.gd.slice.call(a,b):_.gd.slice.call(a,b,c)};_.sd=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};td=function(a,b){return a<b?-1:a>b?1:0};_.ud=function(a,b){return-1!=a.indexOf(b)};_.vd=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
_.wd=function(a,b){for(var c=0,d=(0,_.sd)(String(a)).split("."),e=(0,_.sd)(String(b)).split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var k=d[g]||"",l=e[g]||"",m=RegExp("(\\d*)(\\D*)","g"),n=RegExp("(\\d*)(\\D*)","g");do{var p=m.exec(k)||["","",""],t=n.exec(l)||["","",""];if(0==p[0].length&&0==t[0].length)break;c=td(0==p[1].length?0:(0,window.parseInt)(p[1],10),0==t[1].length?0:(0,window.parseInt)(t[1],10))||td(0==p[2].length,0==t[2].length)||td(p[2],t[2])}while(0==c)}return c}; _.xd=function(a){a.ia=function(){return a.jw?a.jw:a.jw=new a}};t:{var zd=_.s.navigator;if(zd){var Ad=zd.userAgent;if(Ad){_.yd=Ad;break t}}_.yd=""}_.Bd=function(a){return(0,_.ud)(_.yd,a)};
var $d;var Wd;var Ud;var Qd;var Pd;var Kd;Kd=function(){return _.s.navigator||null};_.Ld=(0,_.Bd)("Opera")||(0,_.Bd)("OPR");_.O=(0,_.Bd)("Trident")||(0,_.Bd)("MSIE");_.Md=(0,_.Bd)("Gecko")&&!(0,_.ud)(_.yd.toLowerCase(),"webkit")&&!((0,_.Bd)("Trident")||(0,_.Bd)("MSIE"));_.Nd=(0,_.ud)(_.yd.toLowerCase(),"webkit");_.Od=_.Nd&&(0,_.Bd)("Mobile");Pd=Kd();Qd=Pd&&Pd.platform||"";_.Cd=(0,_.ud)(Qd,"Mac");_.Dd=(0,_.ud)(Qd,"Win");_.Ed=(0,_.ud)(Qd,"Linux");_.Fd=!!Kd()&&(0,_.ud)(Kd().appVersion||"","X11");
var Rd=_.yd;_.Gd=!!Rd&&(0,_.ud)(Rd,"Android");_.Jd=!!Rd&&(0,_.ud)(Rd,"iPhone");_.Sd=!!Rd&&(0,_.ud)(Rd,"iPad");Ud=function(){var a=_.s.document;return a?a.documentMode:void 0};_.Vd=function(){var a="",b;if(_.Ld&&_.s.opera)return a=_.s.opera.version,(0,_.Qc)(a)?a():a;_.Md?b=/rv\:([^\);]+)(\)|;)/:_.O?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:_.Nd&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(_.yd))?a[1]:"");return _.O&&(b=Ud(),b>(0,window.parseFloat)(a))?String(b):a}();Wd={}; _.Xd=function(a){return Wd[a]||(Wd[a]=0<=(0,_.wd)(_.Vd,a))};_.Zd=function(a){return _.O&&_.Yd>=a};$d=_.s.document;_.Yd=$d&&_.O?Ud()||("CSS1Compat"==$d.compatMode?(0,window.parseInt)(_.Vd,10):5):void 0;

var Yg;var Xg;var Ug;Ug=function(a){return Array.prototype.join.call(arguments,"")};_.Vg=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};_.Wg=function(a,b,c,d,e,f,g){var k="";a&&(k+=a+":");c&&(k+="//",b&&(k+=b+"@"),k+=c,d&&(k+=":"+d));e&&(k+=e);f&&(k+="?"+f);g&&(k+="#"+g);return k};Xg=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");
_.Zg=function(a){if(Yg){Yg=!1;var b=_.s.location;if(b){var c=b.href;if(c&&(c=(c=(0,_.Zg)(c)[3]||null)&&(0,window.decodeURIComponent)(c))&&c!=b.hostname)throw Yg=!0,Error();}}return a.match(Xg)};Yg=_.Nd;_.$g=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};
_.ah=function(a,b,c){if((0,_.ka)(b))for(var d=0;d<b.length;d++)(0,_.ah)(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",(0,window.encodeURIComponent)(String(b)))};_.bh=function(a,b){for(var c in b)(0,_.ah)(c,b[c],a);return a};_.ch=function(a,b){(0,_.Vg)(a,"/")&&(a=a.substr(0,a.length-1));(0,_.Vc)(b,"/")&&(b=b.substr(1));return Ug(a,"/",b)};

var rk;var nk;var lk;var jk;var hk;var gk;var ak;var Zj;var Xj;var Uj;var Tj;var Sj;var Qj;Qj=function(a){if(!(0,_.Wc)(a))return null;for(var b={},c=0;c<a.length;c++)b[a[c]]=a[c];return b};
_.Rj=function(a){a=String(a||"").split("\x00").join("");for(var b=[],c=0,d=a.length;c<d;++c){var e=a.charAt(c),f=a.charCodeAt(c);if(55296<=f&&56319>=f&&c+1<d){var g=a.charAt(c+1),k=a.charCodeAt(c+1);56320<=k&&57343>=k&&(e+=g,f=65536+(f-55296<<10)+(k-56320),++c)}if(!(0<=f&&1114109>=f)||55296<=f&&57343>=f||64976<=f&&65007>=f||65534==(f&65534))f=65533,e=String.fromCharCode(f);g=!(32<=f&&126>=f)||" "==e||":"==e||"\\"==e;"%"==e&&(c+2>=d?g=!0:(k=16*(0,window.parseInt)(a.charAt(c+1),16)+(0,window.parseInt)(a.charAt(c+
2),16),0<=k&&255>=k?(f=k,e=0==f?"":"%"+(256+k).toString(16).toUpperCase().substr(1),c+=2):g=!0));g&&(e=(0,window.encodeURIComponent)(e),1>=e.length&&(0<=f&&127>=f?e="%"+(256+f).toString(16).toUpperCase().substr(1):(f=65533,e=(0,window.encodeURIComponent)(String.fromCharCode(f)))));b.push(e)}a=b.join("");a=a.split("#")[0];a=a.split("?");b=a[0].split("/");e=[];c=0;for(d=b.length;c<d;++c)f=b[c],g=f.split("%2E").join("."),g=g.split((0,window.encodeURIComponent)("\uff0e")).join("."),"."==g?c+1==d&&e.push(""):
".."==g?(0<e.length&&e.pop(),c+1==d&&e.push("")):e.push(f);a[0]=e.join("/");for(a=a.join("?");a&&"/"==a.charAt(0);)a=a.substr(1);return"/"+a};Sj=function(a,b){var c=a.length;if(c!=b.length)return!1;for(var d=0;d<c;++d){var e=a.charCodeAt(d),f=b.charCodeAt(d);65<=e&&90>=e&&(e+=32);65<=f&&90>=f&&(f+=32);if(e!=f)return!1}return!0};Tj=null;Uj=null;
_.Vj=function(a){if(null===Tj){var b=(0,_.J)("client/headers/response");b||(b=(0,_.J)("googleapis/headers/response"));Tj=Qj(b)}if(null!=Tj){if(Tj.hasOwnProperty(a))return!0;for(var c in Tj)if(Tj.hasOwnProperty(c)&&Sj(c,a))return!0}return!1};_.Wj=function(a,b){for(var c=0,d=b.length;c<d;++c){var e=b.charCodeAt(c);if(!(32<=e&&126>=e))return!1}null===Uj&&((c=(0,_.J)("client/headers/request"))||(c=(0,_.J)("googleapis/headers/request")),Uj=Qj(c));return null!=Uj?Uj.hasOwnProperty(a):!1};
Xj=function(a,b){if(null!=a)for(var c in a)if(a.hasOwnProperty(c)&&Sj(c,b))return{name:c,value:a[c]}};_.fk=["headers","applicationName","clientVersion","urlParams"];gk=function(a,b,c){c=c||"0.1";b=b||"google-api-javascript-client";var d=[];a&&(d.push(a),d.push(" "));d.push(b);c&&(d.push("/"),d.push(c));return d.join("")};hk=function(){try{return new window.XMLHttpRequest}catch(a){}try{return new window.ActiveXObject("Msxml2.XMLHTTP")}catch(b){}return null};
_.ik=function(a){return(a=a.OriginToken)&&5<a.length?a.substring(a.length-5):a};jk=function(a){if(!a.OriginToken){var b=_.K.nb();(b=b?b.pvt:null)&&(a.OriginToken=b)}};
_.kk=function(a){var b=(0,_.Rj)(a);if(String(a)!=b)throw Error("w");(a=b)&&"/"==a.charAt(a.length-1)||(a=(a||"")+"/");void 0!=_.Yj&&0<_.Yj||(void 0==_.Yj&&_.M.register("init",function(){(0,_.kk)(a)}),Zj=a,ak=_.K.nb(window.location.href),_.Yj=ak.isProxyShared&&(0,window.parseInt)(ak.superBatchSize,10)||0,_.bk=[],_.ck=[],_.ek=_.dk=void 0,(b=(0,window.parseInt)(ak.superBatchTimeout,10)||0)&&ak.isProxyShared&&lk(b,function(){0!=_.Yj&&(0,_.mk)()}))};lk=function(a,b){window.setTimeout(b,a)};
nk=function(){return function(a){a=(0,_.bc)(a);for(var b={},c=0;c<a.length;c++)b[a[c].id]=a[c];for(c=0;c<_.bk.length;c++){for(var d=_.bk[c].requests,e=[],f=0;f<d.length;f++){a=b[d[f].id];var g=a.id;a.id=g.substring(g.indexOf("|")+1);e.push(a)}_.ck[c]((0,_.ac)(e))}}};_.mk=function(){if(0<_.bk.length){for(var a=[],b=0;b<_.bk.length;b++)a=a.concat(_.bk[b].requests);for(var c=_.bk[0],a={requests:a},b=0;b<_.fk.length;++b){var d=_.fk[b];a[d]=c[d]}(0,_.ok)(a,nk(),_.dk,_.ek)}_.Yj=0};
rk=function(a,b,c,d){var e=Xj(b,"X-Goog-Safety-Encoding");if(null!=e){if(pk)a=window.atob(a);else{if(!qk){var f="ABCDEFGHIJKLMNOPQRSTUVWXYZ",f=f+(f.toLowerCase()+"0123456789+/=");qk={};for(var g=0;g<f.length;g++)qk[f.charAt(g)]=g}for(var f=qk,g=[],k=0;k<a.length;){var l=f[a.charAt(k++)],m=k<a.length?f[a.charAt(k)]:0;++k;var n=k<a.length?f[a.charAt(k)]:0;++k;var p=k<a.length?f[a.charAt(k)]:0;++k;if(null==l||null==m||null==n||null==p)throw Error();g.push(l<<2|m>>4);64!=n&&(g.push(m<<4&240|n>>2),64!=
p&&g.push(n<<6&192|p))}a=String.fromCharCode.apply(null,g)}f=Xj(b,"X-Goog-Safety-Content-Type");b["Content-Type"]=f.value;delete b[e.name];delete b[f.name]}return{body:a,headers:b,status:c,statusText:d}};
_.sk=function(a,b,c,d){a=a||{};var e=a.headers||{},f=a.httpMethod||"GET",g=String(a.url||""),k=a.urlParams||null,l=a.body||null,m=a.applicationName||null,n=a.clientName||null,p=a.clientVersion||null;c=c||null;d=d||null;g=(0,_.Rj)(g);g=Zj+String(g||"/").substr(1);g=(0,_.$g)((0,_.bh)([g],k));e["X-JavaScript-User-Agent"]=gk(m,n,p);jk(e);delete e["X-Origin"];c&&(e["X-Origin"]=c);delete e["X-Referer"];d&&(e["X-Referer"]=d);e["X-Goog-Encode-Response-If-Executable"]="base64";l&&"object"===typeof l&&(l=(0,_.ac)(l));
var t=hk();if(!t)throw Error("x");t.open(f,g);t.onreadystatechange=function(){if(4==t.readyState&&0!==t.status){var a=t.responseText;var c=t.getAllResponseHeaders(),d={};if(c)for(var c=c.split("\r\n"),e=0;e<c.length;e++){var f=c[e],g=f.indexOf(": ");if(0<g){var k=f.substring(0,g),f=f.substring(g+2);(0,_.Vj)(k)&&(d[k]=f)}}a=rk(a,d,t.status,t.statusText);b(a)}};t.onerror=function(){var c;c={error:{code:-1,message:"A network error occurred, and the request could not be completed."}};if("/rpc"==a.url){for(var d=
a.body,e=[],f=0;f<d.length;f++){var g=(0,_.ac)(c),g=(0,_.bc)(g);g.id=d[f].id;e.push(g)}c=e}c=(0,_.ac)(c);c=rk(c);b(c)};for(var y in e)e.hasOwnProperty(y)&&(f=e[y],(0,_.Wj)(y,f)&&t.setRequestHeader(y,f));t.send(l?l:null)};
_.ok=function(a,b,c,d){var e={sid:_.nj.get("SID")};b=b||function(){};a=a||{};var f=a.headers||{},g=a.requests||[],k=a.applicationName||null,l=a.clientName||null,m=a.clientVersion||null;_.K.nb();f["Content-Type"]="application/json";var n=(0,_.ik)(f);n&&(e.userToken=n);(0,_.sk)({headers:f,body:g,httpMethod:"POST",url:"/rpc",urlParams:a.urlParams,applicationName:k,clientName:l,clientVersion:m},function(a){b(a.body)},c,d)};
var qk=null,pk="function"==typeof window.atob;
_.oj=function(){function a(){e[0]=1732584193;e[1]=4023233417;e[2]=2562383102;e[3]=271733878;e[4]=3285377520;n=m=0}function b(a){for(var b=g,c=0;64>c;c+=4)b[c/4]=a[c]<<24|a[c+1]<<16|a[c+2]<<8|a[c+3];for(c=16;80>c;c++)a=b[c-3]^b[c-8]^b[c-14]^b[c-16],b[c]=(a<<1|a>>>31)&4294967295;a=e[0];for(var d=e[1],f=e[2],k=e[3],l=e[4],m,n,c=0;80>c;c++)40>c?20>c?(m=k^d&(f^k),n=1518500249):(m=d^f^k,n=1859775393):60>c?(m=d&f|k&(d|f),n=2400959708):(m=d^f^k,n=3395469782),m=((a<<5|a>>>27)&4294967295)+m+l+n+b[c]&4294967295,
l=k,k=f,f=(d<<30|d>>>2)&4294967295,d=a,a=m;e[0]=e[0]+a&4294967295;e[1]=e[1]+d&4294967295;e[2]=e[2]+f&4294967295;e[3]=e[3]+k&4294967295;e[4]=e[4]+l&4294967295}function c(a,c){if("string"===typeof a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var d=[],e=0,g=a.length;e<g;++e)d.push(a.charCodeAt(e));a=d}c||(c=a.length);d=0;if(0==m)for(;d+64<c;)b(a.slice(d,d+64)),d+=64,n+=64;for(;d<c;)if(f[m++]=a[d++],n++,64==m)for(m=0,b(f);d+64<c;)b(a.slice(d,d+64)),d+=64,n+=64}function d(){var a=[],
d=8*n;56>m?c(k,56-m):c(k,64-(m-56));for(var g=63;56<=g;g--)f[g]=d&255,d>>>=8;b(f);for(g=d=0;5>g;g++)for(var l=24;0<=l;l-=8)a[d++]=e[g]>>l&255;return a}for(var e=[],f=[],g=[],k=[128],l=1;64>l;++l)k[l]=0;var m,n;a();return{reset:a,update:c,M:d,uf:function(){for(var a=d(),b="",c=0;c<a.length;c++)b+="0123456789ABCDEF".charAt(Math.floor(a[c]/16))+"0123456789ABCDEF".charAt(a[c]%16);return b}}};

var wk;var vk;var uk;var tk;tk=function(a,b){for(var c in a)if(a[c]!==b[c])return!1;return!0};uk=function(a,b){for(var c=a.requests,d=0;d<c.length;d++)c[d].id=String(_.Yj)+"|"+c[d].id;_.bk.push(a);_.ck.push(b)};
vk=function(a,b,c,d){if(0<_.Yj){if(0<_.bk.length){for(var e=_.bk[0],f=0;f<_.fk.length;++f){var g=_.fk[f],k=a[g],g=e[g];if(!(k===g||"object"==typeof g&&tk(k,g)&&tk(g,k)))break}f==_.fk.length&&c==_.dk?uk(a,b):(0,_.ok)(a,b,c,d)}else uk(a,b),_.dk=c,_.ek=d;0==--_.Yj&&(0,_.mk)()}else(0,_.ok)(a,b,c,d)};wk=function(a,b,c,d){var e={},f=0;if(0==a.length)b(e);else{var g=function(k){var l=k.key;(0,_.sk)(k.params,function(c){e[l]={data:c};f++;a.length==f?b((0,_.ac)(e)):g(a[f])},c,d)};g(a[f])}};_.Ai=_.Ai||{};
_.Ai.Ix=function(a,b){_.M.register(a,function(a){b.call(this,a,this.callback,this.origin,this.referer)})};_.Ai.$a=function(){var a=String(window.location.pathname);18<=a.length&&"/static/proxy.html"==a.substr(a.length-18)&&(a=a.substr(0,a.length-18));a||(a="/");_.Ai.hw(a)};_.Ai.hw=function(a){var b=(0,_.Rj)(a);if(String(a)!=b)throw Error("w");_.Ai.Ix("makeRequest",vk);_.Ai.Ix("makeHttpRequests",wk);(0,_.kk)(a);_.M.call("..","ready:"+_.M.lj(".."))};
_.Ai.gI=function(a){a=a.replace(/\r\n/g,"\n");for(var b=[],c=0,d=0;d<a.length;d++){var e=a.charCodeAt(d);128>e?b[c++]=e:(2048>e?b[c++]=e>>6|192:(b[c++]=e>>12|224,b[c++]=e>>6&63|128),b[c++]=e&63|128)}return b};_.Ai.kQ=function(a){var b=(0,_.oj)();b.update(_.Ai.gI(a));return b.uf()};
(0,_.G)("googleapis.ApiServer.getUserToken",_.ik);(0,_.G)("googleapis.ApiServer.makeHttpRequests",wk);(0,_.G)("googleapis.ApiServer.makeRequest",vk);(0,_.G)("googleapis.ApiServer.initWithPath",_.kk);(0,_.G)("googleapis.server.init",_.Ai.$a);(0,_.G)("googleapis.server.initWithPath",_.Ai.hw);

});
// Google Inc.
